name: tracking_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 8.0.2
  injectable: 2.5.0
  flutter_secure_storage: 9.2.2
  overlay_support: 2.1.0
  is_first_run: 1.0.0
  dio: 5.7.0
  shared_preferences: 2.3.3
  logger: 2.5.0
  intl: 0.20.1
  freezed_annotation: 2.4.4
  dartx: 1.2.0
  retrofit: 4.4.0
  json_annotation: 4.9.0
  flutter_bloc: 8.1.6
  dartz: 0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  injectable_generator: 2.6.2
  build_runner: 2.4.13
  retrofit_generator: 9.1.5
  json_serializable: 6.9.0
  freezed: 2.5.7
  flutter_gen_runner: 5.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
  arb_dir: assets/l10n
  output_dir: lib/generated

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/generated 
  line_length: 80
  assets:
    output:
      enabled: true
      package_parameter_enabled: false